### ISSUE TITLE
`export_scalars_to_json` works with `add_scalars` but not `add_scalar`

### ISSUE THREAD

**Issue by aasseman** [lanpa/tensorboard-pytorch#135]
- logging scalars using `add_scalar`, and running `export_scalars_to_json` at the end of my experiment leads to an empty json file (contains just "{}")
- logging scalars using `add_scalars`, `export_scalars_to_json` works as expected.

I want to use `add_scalar` because it can log all the scalars to a single tensorboard file.

I am using PyTorch 0.4 with tensorboardX 1.2

**Comment by lanpa** [comment]
Hi, this feature is removed in c9a84bc to prevent memory from explosion in some cases. You can use tensorboardX1.1 or re-add that line in 1.2's sources code and then install from source.

**Comment by simonhessner** [comment]
I think this should be covered in the docs https://tensorboardx.readthedocs.io/en/latest/tensorboard.html

**Comment by MicaelCarvalho** [comment]
Hi,

I don't understand this behavior... Let me check the facts again:
1. As of c9a84bc32e2ca17d7bd2446736088a6181ecf5b6, `add_scalar` no longer keeps scalars in the scalar dict
2. There is no way of adding a list of scalars for both `x` and `y` in the form add_scalar('name', [1,2,3], [2,3,4])
3. Supposedly, one should use `add_scalars` in order to keep them in memory, but it adds considerable overhead to achieve the same functionality of `add_scalar` (creating useless dicts and concatenating tag names)

And, if I understood correctly, because `add_scalar` doesn't keep them in the dict, it is impossible to export anything that went through it. The only solution would be to use `add_scalars` (with all its bad points) and call `export_scalars_to_json`.

Is this correct? If so, shouldn't `add_scalar` simply have an extra boolean argument for keeping things in the dict or not? Instead of dropping support to exporting scalars altogether.
