### ISSUE TITLE
Incorporate `add_embedding` into SummaryWriter

### ISSUE THREAD

**Issue by Stonesjtu** [lanpa/tensorboard-pytorch#5]
Some advantages to implement it in SummaryWriter:
  - More general and uniform APIs to use.
  - Manage all the embeddings under one dir: `runs/XXX` (currently the embedding must be written into separate directories.
  - Don't have to run different tensorboard instances for **embedding visualization** and other **summary info**

And in your README.txt, the add_embedding is under `SummaryWriter` part.

If the original tensorboard don't have such mechanism, we can wrap the `SummaryWriter` and `add_embedding` into brand new unified APIs.

**Comment by lanpa** [comment]
The reason to separate embedding from other functions is that this function uses tensorflow's internal code to dump data, rather then `SummaryWriter`. (Because I fiddled around but in vain) And currently, the embedding folder depth can only be 1. This is a documented bug in a ongoing [tutorial](https://medium.com/@dexterhuang/tensorboard-for-pytorch-201a228533c5). XD. Another concern is https://github.com/pytorch/pytorch/issues/2230, which breaks training procedure if you are using multi GPU, so I think it is still a premature porting. Finally, official tensorboard seems to unify data format as [`tensorSummary`](https://github.com/tensorflow/tensorboard/issues/296), if that comes true, we can solve the above problems at once then put it back to  `SummaryWriter` class.
