### ISSUE TITLE
package name conflict

### ISSUE THREAD

**Issue by edgarriba** [lanpa/tensorboard-pytorch#8]
there's a conflict with package names at loading time when you install the standalone version of tensorboard from: https://github.com/dmlc/tensorboard

The use case is to not have to install tensorflow, since that's whole point of using pytorch. Any workaround for this? I'd would be more intuitive to rename the module to `tensorboard-pytorch`

**Comment by lanpa** [comment]
Hi, the point of this package is to make use of tensorboard's feature, instead of getting rid of TF. I think most researcher have both pytorch and tensorflow in a single machine. :) Additionally, to use function such as add_embedding, you still need tensorflow installed at this time. 

And there will be a more generic version in the future (supports Theano, numpy), so I would like to have a module name without a specific postfix. Please suggest if you have good idea. 

A easy workaround of conflict will be https://stackoverflow.com/questions/27532112/how-to-handle-python-packages-with-conflicting-names, or rename the `tensorboard` folder to  `tensorboard-pytorch` folder and build by yourself.

**Comment by edgarriba** [comment]
Thanks for the answer. The first solution looks good, however the second one should be the way to go since overlapping package names in general is a bad practice. Besides, if you want to give support to other frameworks you will have to rename the package because it won't be pytorch specific anymore.
