### ISSUE TITLE
add_graph_onnx not working

### ISSUE THREAD

**Issue by ahundt** [lanpa/tensorboard-pytorch#80]
Maybe this is something that would be fixed with a new release on pip?

I had the following code:
```
writer.add_graph(model, images[:2])
```
I got the following warning:
```
± python a1_mnist_fashion.py
warning: Embedding dir exists, did you set global_step for add_embedding()?
You are using PyTorch==0.3, use add_graph_onnx()
```
so I changed my code to:
```
# add the graph to tensorboard for visualization
writer.add_graph_onnx(model)
```
and then I got: 
```
± python a1_mnist_fashion.py
warning: Embedding dir exists, did you set global_step for add_embedding()?
Traceback (most recent call last):
  File "a1_mnist_fashion.py", line 129, in <module>
    writer.add_graph_onnx(model)
  File "/home/ahundt/.local/lib/python2.7/site-packages/tensorboardX/writer.py", line 377, in add_graph_onnx
    self.file_writer.add_graph_onnx(gg(prototxt))
  File "/home/ahundt/.local/lib/python2.7/site-packages/tensorboardX/graph_onnx.py", line 11, in gg
    m = onnx.load(fname)
  File "/home/ahundt/.local/lib/python2.7/site-packages/onnx/__init__.py", line 29, in load
    with open(obj, 'rb') as f:
TypeError: coercing to Unicode: need string or buffer, Net found
-> [1]
```

**Comment by lanpa** [comment]
Looks like an onnx problem. (`onnx/__init__.py`)

How did you install onnx? `add_graph_onnx` should generate a `*.proto` file in the working folder, can you upload it as well?

ps. since the variable's scope information is not stored in onnx, I suggest you build PyTorch 0.4 and use default `add_graph` for better visualization.

**Comment by ahundt** [comment]
just wrote `pip2 install onnx --user --upgrade`. This is in a bit of code I'm going to use to TA a class, so while I'd normally have no problem upgrading it looks like [only 0.3 is actually released](https://github.com/pytorch/pytorch/releases). Trying to teach 90 students to install pre-release code from source would probably not be a good way to go. :-/

**Comment by ahundt** [comment]
I can probably just skip the graph if needed, that part of the visualization was really just a nice to have. 

Oh also the histogram bias values don't seem to show up correctly, they show up as a single centered spike, unlike [other examples which I've seen which have a nice distribution](https://github.com/yunjey/pytorch-tutorial/tree/master/tutorials/04-utils/tensorboard).

![tensorboard unusual bias etc 2018-02-08 21-39-44](https://user-images.githubusercontent.com/55744/36009126-cae9998e-0d18-11e8-865d-b466656fc1fe.png)

**Comment by lanpa** [comment]
I am happy to see this package might be used in a big class! As for `add_graph()`, it should work with pytorch release 0.3.1. (https://github.com/pytorch/pytorch/issues/4821) 

The histogram problem can be solved by adding additional parameter `writer.add_histogram(name, param, n_iter, bins='doane')`. I just tested this with ordinary mnist example and it works well. 
https://gist.github.com/lanpa/0f6a1e382468030e67e9faff25db3cb5

**Comment by amorgun** [comment]
@lanpa Sadly `add_graph()` is not working with 0.3.1 because of signature mismatch:
1) https://github.com/lanpa/tensorboard-pytorch/blob/0c9f7ba28b37e4f22f269e4350e1c5813a3b5634/tensorboardX/graph.py#L45 - two arguments are used
2) https://github.com/pytorch/pytorch/blob/v0.3.1/torch/onnx/__init__.py#L78 - only one argument is allowed
Also, [that check](https://github.com/lanpa/tensorboard-pytorch/blob/0c9f7ba28b37e4f22f269e4350e1c5813a3b5634/tensorboardX/writer.py#L391-L399) does not allow to use `add_graph()` in 0.3.1.

**Comment by ahundt** [comment]
Cool would you mind updating pypi since that fix was merged?

**Comment by lanpa** [comment]
Hi, please have a test~
